### PR TITLE
Brought tabs more in line with atom dark

### PR DESCRIPTION
**Pull request by GU5TAF**
atom dark tabs

* Added blue indicator on the left
* Added slight gradient overlay and inner glow to active tab
* Added gradient separator between each tab
* Added animated close icon that shows on hover

It's pretty much exactly 1 to 1 with the atom dark theme.

### CODE REVIEW

**Comment by GU5TAF** [comment]
Any chance you'll merge this @mdo?

**Comment by zpnk** [comment]
Nice work @GU5TAF, thanks! @mdo can we land this please? 😀

**Comment by lowmess** [comment]
@GU5TAF looks like a recent change is causing some merge conflicts. I'd really like to see this get merged/published. Any chance on a fix?

**Comment by GU5TAF** [comment]
Should be good to go now @lowmess 😉

**Pull request merged**
